/**
 * Secure Backend Proxy Server (Node.js & Express)
 * 
 * DESIGN PRINCIPLES:
 * 1. Zero Trust: Expose no credentials, internal paths, or direct 3rd-party error payloads to the client.
 * 2. Origin Hardening (CORS): Strictly permit only authorized clients/origins to trigger the proxy.
 * 3. Abuse Prevention: Rate limit by client IP to prevent bot abuse, DDOS, and third-party API bill inflation.
 * 4. Error Masking: Safely capture 3rd-party API errors, log full diagnostics on the server, and return
 *    sterile, sanitized error responses to the browser.
 */

const express = require('express');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const crypto = require('crypto');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// ==========================================
// 1. INPUT PARSING & BODY-SIZE CONTROLS
// ==========================================
// Restrict JSON payload size to prevent memory-exhaustion / DOS attempts.
app.use(express.json({ limit: '10kb' }));

// ==========================================
// 2. HARDENED CORS CONFIGURATION
// ==========================================
const ALLOWED_ORIGINS = process.env.ALLOWED_ORIGINS 
  ? process.env.ALLOWED_ORIGINS.split(',') 
  : ['http://localhost:3000', 'http://localhost:5173']; // Default react/vite/next local dev origins

const corsOptions = {
  origin: (origin, callback) => {
    // Allow server-to-server or REST tool requests (origin will be undefined) in development if specified
    if (!origin && process.env.NODE_ENV === 'development') {
      return callback(null, true);
    }
    if (ALLOWED_ORIGINS.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error('Blocked by CORS policy: Unauthorized origin.'));
    }
  },
  methods: ['POST'], // Only allow POST requests for proxy operations
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true,
  optionsSuccessStatus: 200
};
app.use(cors(corsOptions));

// ==========================================
// 3. SECURE RATE LIMITING (ABUSE PROTECTION)
// ==========================================
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes window
  max: 100, // Limit each IP to 100 requests per window
  standardHeaders: true, // Return standard rate limit info headers
  legacyHeaders: false, // Disable X-RateLimit-* headers
  message: {
    error: 'Too many requests. Please slow down and try again later.',
    status: 429
  },
  handler: (req, res, next, options) => {
    // Log rate-limiting events for security ops auditing
    console.warn(`[SECURITY ALERT] Rate limit exceeded for IP: ${req.ip} on route: ${req.originalUrl}`);
    res.status(options.statusCode).json(options.message);
  }
});
app.use('/api', apiLimiter);

// ==========================================
// 4. SECURE PROXY ROUTE (Forwarding to OpenAI API)
// ==========================================
app.post('/api/v1/chat', async (req, res, next) => {
  const correlationId = crypto.randomUUID();
  console.log(`[${correlationId}] Incoming proxy request from IP: ${req.ip}`);

  try {
    const { messages, model, temperature } = req.body;

    // Validate request structure (Fail Fast)
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ 
        error: 'Invalid payload structure. "messages" array is required.' 
      });
    }

    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      console.error(`[${correlationId}] Server configuration error: OPENAI_API_KEY is missing in env.`);
      throw new Error('API key unconfigured on server.');
    }

    // Smart Mocking Mode for local testing/verification without paid keys
    if (apiKey.includes('testkey') || apiKey.includes('mock')) {
      console.log(`[${correlationId}] [MOCK MODE] Simulating OpenAI chat completion response.`);
      // Delay slightly to simulate network latency (300ms)
      await new Promise(resolve => setTimeout(resolve, 300));
      
      const userMessage = messages[messages.length - 1]?.content || "";
      const simulatedText = `[Secure Proxy Simulated Response] Received: "${userMessage}". This is a mock response generated by your secure backend proxy server. The proxy successfully intercepted your CORS origin, validated rate-limits, and executed this logic on the server-side without exposing your environment keys to the browser!`;

      const mockPayload = {
        id: `chatcmpl-mock-${crypto.randomBytes(8).toString('hex')}`,
        model: model || 'gpt-4o-mini',
        choices: [{
          index: 0,
          message: {
            role: 'assistant',
            content: simulatedText
          },
          finish_reason: 'stop'
        }],
        usage: {
          prompt_tokens: userMessage.split(' ').length,
          completion_tokens: simulatedText.split(' ').length,
          total_tokens: userMessage.split(' ').length + simulatedText.split(' ').length
        }
      };

      console.log(`[${correlationId}] [MOCK MODE] Mock request completed successfully.`);
      return res.status(200).json(mockPayload);
    }

    // Configure the external outgoing request safely
    const thirdPartyUrl = 'https://api.openai.com/v1/chat/completions';
    const response = await fetch(thirdPartyUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: model || 'gpt-4o-mini',
        messages: messages.map(m => ({ role: m.role, content: m.content })), // Sanitize body inputs
        temperature: typeof temperature === 'number' ? temperature : 0.7
      })
    });

    const data = await response.json();

    // Check if the third-party API returned an error status
    if (!response.ok) {
      // Log details internally on the server (do not leak to client)
      console.error(`[${correlationId}] Third-party API error (${response.status}):`, JSON.stringify(data));
      
      // Mask third party errors securely
      return res.status(response.status).json({
        error: `Third-party service error. Please try again later.`,
        referenceId: correlationId // Give the user an audit code to lookup in server logs
      });
    }

    // Return ONLY the sanitized data payload needed by the client
    // Strip out unnecessary billing tokens, system fields, or metadata if desired
    const sanitizedPayload = {
      id: data.id,
      model: data.model,
      choices: data.choices.map(c => ({
        index: c.index,
        message: {
          role: c.message.role,
          content: c.message.content
        },
        finish_reason: c.finish_reason
      })),
      usage: data.usage // Safe to return usage for tracking but completely key-free!
    };

    console.log(`[${correlationId}] Proxy request completed successfully.`);
    return res.status(200).json(sanitizedPayload);

  } catch (error) {
    // Pass unexpected errors to the global error masking middleware
    error.correlationId = correlationId;
    next(error);
  }
});

// ==========================================
// 5. GLOBAL SECURITY ERROR-MASKING MIDDLEWARE
// ==========================================
app.use((err, req, res, next) => {
  const correlationId = err.correlationId || crypto.randomUUID();
  
  // Log the complete diagnostic error, stack trace, and context safely on the server
  console.error(`[FATAL EXCEPTION][Ref: ${correlationId}]`, {
    message: err.message,
    stack: err.stack,
    path: req.originalUrl,
    method: req.method,
    ip: req.ip
  });

  // If it's a CORS policy block, return a 403 Forbidden error response
  if (err.message && err.message.includes('CORS')) {
    return res.status(403).json({
      error: 'Access Denied: CORS policy violation.',
      referenceId: correlationId
    });
  }

  // Return a completely masked, sterile 500 error to the client
  // Under no circumstances leak DB connections, stack traces, local paths, or internal configurations
  res.status(500).json({
    error: 'A secure system error occurred. Our engineers have been notified.',
    referenceId: correlationId
  });
});

// ==========================================
// 6. SERVER ACTIVATION
// ==========================================
app.listen(PORT, () => {
  console.log(`===========================================================`);
  console.log(`  Secure Backend Proxy activated successfully!`);
  console.log(`  Running on: http://localhost:${PORT}`);
  console.log(`  Target Allowed Origins: ${ALLOWED_ORIGINS.join(', ')}`);
  console.log(`===========================================================`);
});
