/* Country Phone Codes — sorted by common usage */

export const countries = [
  { code: "+91", country: "India", flag: "🇮🇳", iso: "IN", maxLen: 10 },
  { code: "+1", country: "United States", flag: "🇺🇸", iso: "US", maxLen: 10 },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧", iso: "GB", maxLen: 10 },
  { code: "+61", country: "Australia", flag: "🇦🇺", iso: "AU", maxLen: 9 },
  { code: "+86", country: "China", flag: "🇨🇳", iso: "CN", maxLen: 11 },
  { code: "+81", country: "Japan", flag: "🇯🇵", iso: "JP", maxLen: 10 },
  { code: "+49", country: "Germany", flag: "🇩🇪", iso: "DE", maxLen: 11 },
  { code: "+33", country: "France", flag: "🇫🇷", iso: "FR", maxLen: 9 },
  { code: "+39", country: "Italy", flag: "🇮🇹", iso: "IT", maxLen: 10 },
  { code: "+7", country: "Russia", flag: "🇷🇺", iso: "RU", maxLen: 10 },
  { code: "+55", country: "Brazil", flag: "🇧🇷", iso: "BR", maxLen: 11 },
  { code: "+82", country: "South Korea", flag: "🇰🇷", iso: "KR", maxLen: 10 },
  { code: "+34", country: "Spain", flag: "🇪🇸", iso: "ES", maxLen: 9 },
  { code: "+52", country: "Mexico", flag: "🇲🇽", iso: "MX", maxLen: 10 },
  { code: "+62", country: "Indonesia", flag: "🇮🇩", iso: "ID", maxLen: 12 },
  { code: "+90", country: "Turkey", flag: "🇹🇷", iso: "TR", maxLen: 10 },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", iso: "SA", maxLen: 9 },
  { code: "+971", country: "UAE", flag: "🇦🇪", iso: "AE", maxLen: 9 },
  { code: "+27", country: "South Africa", flag: "🇿🇦", iso: "ZA", maxLen: 9 },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", iso: "NG", maxLen: 10 },
  { code: "+254", country: "Kenya", flag: "🇰🇪", iso: "KE", maxLen: 9 },
  { code: "+63", country: "Philippines", flag: "🇵🇭", iso: "PH", maxLen: 10 },
  { code: "+84", country: "Vietnam", flag: "🇻🇳", iso: "VN", maxLen: 9 },
  { code: "+66", country: "Thailand", flag: "🇹🇭", iso: "TH", maxLen: 9 },
  { code: "+60", country: "Malaysia", flag: "🇲🇾", iso: "MY", maxLen: 10 },
  { code: "+65", country: "Singapore", flag: "🇸🇬", iso: "SG", maxLen: 8 },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰", iso: "HK", maxLen: 8 },
  { code: "+886", country: "Taiwan", flag: "🇹🇼", iso: "TW", maxLen: 9 },
  { code: "+48", country: "Poland", flag: "🇵🇱", iso: "PL", maxLen: 9 },
  { code: "+46", country: "Sweden", flag: "🇸🇪", iso: "SE", maxLen: 9 },
  { code: "+47", country: "Norway", flag: "🇳🇴", iso: "NO", maxLen: 8 },
  { code: "+45", country: "Denmark", flag: "🇩🇰", iso: "DK", maxLen: 8 },
  { code: "+358", country: "Finland", flag: "🇫🇮", iso: "FI", maxLen: 10 },
  { code: "+31", country: "Netherlands", flag: "🇳🇱", iso: "NL", maxLen: 9 },
  { code: "+32", country: "Belgium", flag: "🇧🇪", iso: "BE", maxLen: 9 },
  { code: "+41", country: "Switzerland", flag: "🇨🇭", iso: "CH", maxLen: 9 },
  { code: "+43", country: "Austria", flag: "🇦🇹", iso: "AT", maxLen: 10 },
  { code: "+351", country: "Portugal", flag: "🇵🇹", iso: "PT", maxLen: 9 },
  { code: "+353", country: "Ireland", flag: "🇮🇪", iso: "IE", maxLen: 9 },
  { code: "+64", country: "New Zealand", flag: "🇳🇿", iso: "NZ", maxLen: 9 },
  { code: "+20", country: "Egypt", flag: "🇪🇬", iso: "EG", maxLen: 10 },
  { code: "+92", country: "Pakistan", flag: "🇵🇰", iso: "PK", maxLen: 10 },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩", iso: "BD", maxLen: 10 },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰", iso: "LK", maxLen: 9 },
  { code: "+977", country: "Nepal", flag: "🇳🇵", iso: "NP", maxLen: 10 },
  { code: "+974", country: "Qatar", flag: "🇶🇦", iso: "QA", maxLen: 8 },
  { code: "+968", country: "Oman", flag: "🇴🇲", iso: "OM", maxLen: 8 },
  { code: "+973", country: "Bahrain", flag: "🇧🇭", iso: "BH", maxLen: 8 },
  { code: "+965", country: "Kuwait", flag: "🇰🇼", iso: "KW", maxLen: 8 },
  { code: "+972", country: "Israel", flag: "🇮🇱", iso: "IL", maxLen: 9 },
];
